In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('../../../data/processed/ZHVI/ZHVI_April24_Processed.csv', dtype=str)

In [3]:
df

,Date,ZHVI,ZipCode,SizeRank,State,City,Metro,CountyName
0,2004-01-31,225082.0,77494,1,TX,Katy,"Houston-The Woodlands-Sugar Land, TX",Fort Bend County
1,2004-02-29,226204.0,77494,1,TX,Katy,"Houston-The Woodlands-Sugar Land, TX",Fort Bend County
2,2004-03-31,227643.0,77494,1,TX,Katy,"Houston-The Woodlands-Sugar Land, TX",Fort Bend County
3,2004-04-30,228472.0,77494,1,TX,Katy,"Houston-The Woodlands-Sugar Land, TX",Fort Bend County
4,2004-05-31,229136.0,77494,1,TX,Katy,"Houston-The Woodlands-Sugar Land, TX",Fort Bend County
...,...,...,...,...,...,...,...,...
3569715,2023-12-31,221449.0,14441,39992,NY,Dresden,"Rochester, NY",Yates County
3569716,2024-01-31,218865.0,14441,39992,NY,Dresden,"Rochester, NY",Yates County
3569717,2024-02-29,216495.0,14441,39992,NY,Dresden,"Rochester, NY",Yates County
3569718,2024-03-31,217303.0,14441,39992,NY,Dresden,"Rochester, NY",Yates County
3569719,2024-04-30,220811.0,14441,39992,NY,Dresden,"Rochester, NY",Yates County

In [4]:
df = df[['Date', 'ZHVI', 'ZipCode']]

In [5]:
df = df[df['Date'] > '2023-04-30']

In [6]:
df.to_csv('../../../data/site/ZHVI_Update_April24_1yr.csv', index= False)